# DataFrame II

In [21]:
import pandas as pd
import datetime as dt

In [24]:
employees = pd.read_csv("employees.csv")
employees.info()
employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees["Gender"]
employees.info()
employees

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    category
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 49.1+ KB

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [26]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [32]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

employees[employees["Gender"] == "Male"]
employees[employees["Team"] == "Finance"]

on_finance_team = employees["Team"] == "Finance"
employees[on_finance_team]

print(id(employees))
print(id(employees[employees["Senior Management"]]))

employees[employees["Salary"] > 110000]
employees[employees["Bonus %"] < 1.5]
employees[employees["Start Date"] < "1985-01-01"]

employees[employees["Last Login Time"] < dt.time(12, 0, 0)]

2637971903680
2637989260576

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [11]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

is_female = employees["Gender"] == "Female"
is_marketing = employees["Team"] == "Marketing"
employees[is_female & is_marketing]
is_high_salary = employees["Salary"] > 100000
employees[is_female & is_marketing & is_high_salary]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,01:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
305,Margaret,Female,1993-02-06,01:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,03:01:00,145988,18.243,False,Marketing
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
468,Janice,Female,1997-06-28,01:48:00,136032,10.696,True,Marketing
490,Judith,Female,2007-11-23,01:22:00,117055,7.461,False,Marketing
531,Virginia,Female,2010-05-02,09:10:00,123649,10.154,True,Marketing
585,Shirley,Female,1988-04-16,11:09:00,132156,2.754,False,Marketing
627,Anne,Female,1984-11-21,12:30:00,128305,16.636,False,Marketing
656,Lisa,Female,1982-02-09,06:44:00,113592,17.108,True,Marketing
675,Diane,Female,2009-10-30,06:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,10:04:00,138925,9.801,True,Marketing
811,Judith,Female,1989-09-03,11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,04:44:00,123621,19.767,True,Marketing
881,Ruby,Female,1980-01-28,11:08:00,142868,6.318,False,Marketing
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing

In [7]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

is_senior = employees["Senior Management"]
is_early = employees["Start Date"] < "1990-01-01"
employees[is_senior | is_early]

is_robert = employees["First Name"] == "Robert"
is_client = employees["Team"] == "Client Services"
is_late = employees["Start Date"] > "2016-06-01"
employees[(is_robert & is_client) | is_late]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
387,Robert,Male,1994-10-29,04:26:00,123294,19.894,False,Client Services
451,Terry,NaN,2016-07-15,12:29:00,140002,19.490,True,Marketing

In [6]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

employees[employees["Team"].isin(["Legal", "Sales", "Product"])]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [10]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

employees[employees["Team"].isnull()]
employees[employees["Team"].notnull()]
missing_first_name = employees["First Name"].isnull()
team_not_null = employees["Team"].notnull()
employees[missing_first_name & team_not_null]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
25,NaN,Male,2012-10-08,01:12:00,37076,18.576,True,Client Services
39,NaN,Male,2016-01-29,02:33:00,122173,7.797,True,Client Services
51,NaN,NaN,2011-12-17,08:29:00,41126,14.009,True,Sales
62,NaN,Female,2007-06-12,05:25:00,58112,19.414,True,Marketing
116,NaN,Male,1991-06-22,08:58:00,76189,18.988,True,Legal
149,NaN,Female,2014-08-17,02:00:00,86230,8.578,True,Distribution
157,NaN,Female,2005-07-27,08:32:00,79536,14.443,True,Product
165,NaN,Female,2014-03-23,01:28:00,59148,9.061,True,Legal
166,NaN,Female,1991-07-09,06:52:00,42341,7.014,True,Sales
174,NaN,NaN,2007-09-18,06:59:00,40297,6.185,True,Client Services
186,NaN,Female,2005-02-23,09:50:00,149654,1.825,True,Sales
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
253,NaN,NaN,2003-04-28,03:01:00,113732,10.391,True,Sales
257,NaN,Male,1999-11-25,06:16:00,42676,15.517,True,Sales
266,NaN,Female,2009-08-05,08:14:00,115145,14.063,True,Distribution
267,NaN,Male,2005-02-04,01:01:00,40451,16.044,True,Distribution
269,NaN,Female,1992-08-02,08:35:00,145316,18.517,True,Human Resources
320,NaN,Female,2008-07-08,11:40:00,62960,14.356,True,Sales
329,NaN,Male,2010-01-27,02:57:00,87760,14.987,True,Engineering
352,NaN,Male,2011-10-09,09:29:00,69906,4.844,True,Engineering
353,NaN,Male,1997-04-22,09:36:00,65078,3.095,True,Marketing
374,NaN,Female,2006-12-31,11:02:00,81444,3.171,True,Distribution
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
416,NaN,Male,2008-06-29,05:23:00,111043,5.966,True,Distribution
444,NaN,Male,2016-05-24,09:17:00,76409,7.008,True,Distribution
454,NaN,Male,1995-02-21,12:26:00,136602,10.429,True,Marketing
481,NaN,Female,2013-04-27,06:40:00,93847,1.085,True,Business Development
483,NaN,Female,1992-04-26,08:01:00,115436,3.099,True,Human Resources
504,NaN,Female,2014-06-24,10:05:00,38275,10.494,True,Distribution
505,NaN,Male,1980-04-20,01:17:00,71520,13.248,True,Engineering
521,NaN,NaN,1981-09-25,09:59:00,83895,17.971,True,Engineering
540,NaN,Female,2009-12-02,03:30:00,84746,4.820,True,Finance
574,NaN,Female,2009-01-13,01:01:00,118736,7.421,True,Client Services
599,NaN,Female,1990-10-11,10:57:00,98385,10.925,True,Human Resources
607,NaN,Male,1983-10-13,11:59:00,139754,12.740,True,Sales
608,NaN,Female,1993-10-24,05:17:00,116236,17.274,True,Engineering
628,NaN,NaN,1988-09-02,12:49:00,147309,1.702,True,Distribution
674,NaN,Male,2012-08-28,07:56:00,88733,1.932,True,Human Resources
685,NaN,Male,1989-10-20,09:37:00,88086,19.387,True,Finance
687,NaN,Male,1996-12-27,07:07:00,139959,8.992,True,Distribution
697,NaN,Male,1990-05-23,02:09:00,136655,9.801,True,Distribution
709,NaN,Male,1995-04-07,04:32:00,60411,12.048,True,Human Resources
733,NaN,Male,2009-06-17,01:00:00,136681,3.655,True,Business Development
734,NaN,Female,1994-12-18,08:42:00,138807,1.400,True,Human Resources
773,NaN,Male,1986-10-24,09:23:00,47176,10.736,True,Finance
782,NaN,Male,1986-05-06,04:41:00,74104,17.680,True,Client Services
783,NaN,NaN,1991-04-15,03:39:00,132505,13.592,True,Product
785,NaN,Female,1982-07-24,12:00:00,57811,8.941,True,Marketing
812,NaN,Male,1994-12-13,10:34:00,141311,5.478,True,Product
821,NaN,Female,1980-12-27,02:27:00,80399,12.254,True,Distribution
823,NaN,Male,2009-11-12,02:30:00,109411,9.494,True,Engineering
877,NaN,Male,1980-09-05,07:36:00,114896,13.823,True,Client Services
890,NaN,Male,2015-11-24,03:11:00,145329,7.100,True,Finance
902,NaN,Male,2001-05-23,07:52:00,103877,6.322,True,Distribution
925,NaN,Female,2000-08-23,04:19:00,95866,19.388,True,Sales
946,NaN,Female,1985-09-15,01:50:00,133472,16.941,True,Distribution
947,NaN,Male,2012-07-30,03:07:00,107351,5.329,True,Marketing

In [24]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"], date_format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees.head()

employees[employees["Salary"].between(left=60000, right=70000)]
employees[employees["Bonus %"].between(2.0, 5.0)]
employees[employees["Start Date"].between("1991-01-01", "1992-01-01")]
employees[employees["Last Login Time"].between(dt.time(8, 30), dt.time(9, 0))]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
36,Rachel,Female,2009-02-16,08:47:00,142032,12.599,False,Business Development
37,Linda,Female,1981-10-19,08:49:00,57427,9.557,True,Client Services
85,Jeremy,Male,2008-02-01,08:50:00,100238,3.887,True,Client Services
96,Cynthia,Female,1994-03-21,08:34:00,142321,1.737,False,Finance
116,NaN,Male,1991-06-22,08:58:00,76189,18.988,True,Legal
121,Kathleen,NaN,2016-05-09,08:55:00,119735,18.740,False,Product
141,Adam,Male,1990-12-24,08:57:00,110194,14.727,True,Product
150,Sean,Male,1996-05-04,08:59:00,135490,19.934,False,Marketing
153,Victor,NaN,2011-03-10,08:40:00,84546,10.489,True,Finance
157,NaN,Female,2005-07-27,08:32:00,79536,14.443,True,Product
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
259,Henry,Male,1995-02-06,08:34:00,89258,15.585,True,Human Resources
269,NaN,Female,1992-08-02,08:35:00,145316,18.517,True,Human Resources
301,James,Male,2015-07-11,08:52:00,72257,13.023,False,Engineering
345,Steven,Male,2006-11-21,08:30:00,83706,6.960,True,Human Resources
350,Thomas,NaN,1995-08-31,08:31:00,41549,3.950,False,Sales
363,Justin,NaN,2005-04-15,08:43:00,96978,13.865,False,Finance
366,Jennifer,NaN,1989-01-24,08:38:00,58520,16.231,True,Client Services
385,Debra,Female,2010-01-19,08:48:00,70492,8.895,False,Client Services
397,Clarence,Male,2005-01-13,09:00:00,116693,13.835,True,Distribution
429,Rose,Female,2015-05-28,08:40:00,149903,5.630,False,Human Resources
432,Jessica,NaN,2015-03-07,08:45:00,121160,12.993,False,Client Services
446,Cheryl,Female,1994-08-16,08:33:00,67150,15.850,True,Marketing
557,Jane,Female,1994-06-01,08:39:00,42424,18.115,False,Distribution
579,Harold,Male,2010-10-18,08:45:00,65673,1.187,True,Legal
654,Carl,Male,1984-12-14,08:49:00,63395,11.411,False,Legal
734,NaN,Female,1994-12-18,08:42:00,138807,1.400,True,Human Resources
807,Mary,Female,2011-11-06,08:32:00,115057,2.089,False,Finance
815,Maria,NaN,1986-01-18,08:36:00,106562,4.000,False,Human Resources
817,Ruby,Female,2008-05-31,08:41:00,83112,4.083,False,Marketing
828,Cynthia,Female,2006-07-12,08:55:00,149684,7.864,False,Product
840,Lillian,Female,2002-08-26,08:53:00,103854,4.924,True,Distribution
852,Diana,Female,2004-11-19,08:47:00,105066,17.343,True,Business Development
885,Juan,Male,1993-10-06,08:52:00,85871,9.160,False,Product
887,David,Male,2009-12-05,08:48:00,92242,15.407,False,Legal
906,Frances,Female,2014-05-16,08:31:00,35884,17.667,False,Sales
922,Arthur,Male,2013-12-05,08:44:00,86615,3.412,True,Business Development
941,William,Male,1997-06-26,08:33:00,104840,15.653,True,Engineering
969,Linda,Female,2010-02-04,08:49:00,44486,17.308,True,Engineering
970,Alice,Female,1988-09-03,08:54:00,63571,15.397,True,Product
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance