# GruopBy

In [1]:
import pandas as pd

In [20]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [16]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
fortune.head()

fortune[fortune["Sector"] == "Retailing"]["Revenue"].sum()
sectors = fortune.groupby("Sector")
sectors
len(sectors)
sectors.size()
sectors.first()
sectors.last()

,Company,Industry,Revenue,Profits,Employees
Sector,,,,,
Aerospace & Defense,Delta Tucker Holdings,Aerospace and Defense,1923,-133,12000
Apparel,Guess,Apparel,2204,82,13500
Business Services,DeVry Education Group,Education,1910,140,11770
Chemicals,H.B. Fuller,Chemicals,2084,87,4425
Energy,Portland General Electric,Utilities: Gas and Electric,1898,172,2646
Engineering & Construction,MDC Holdings,Homebuilders,1909,66,1225
Financials,New York Community Bancorp,Commercial Banks,1902,-47,3448
Food and Drug Stores,Fred’s,Food and Drug Stores,2151,-7,7103
"Food, Beverages & Tobacco",Alliance One International,Tobacco,2066,-15,6835
Health Care,Providence Service,Health Care: Pharmacy and Other Services,1987,84,9072
"Hotels, Resturants & Leisure",Wendy’s,Food Services,1896,161,21200
Household Products,Revlon,Household and Personal Products,1914,56,5700
Industrials,Briggs & Stratton,Industrial Machinery,1895,46,5480
Materials,Schnitzer Steel Industries,Metals,1924,-197,2955
Media,Cenveo,"Publishing, Printing",1921,-31,7300
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,1986,182,2700
Retailing,99 Cents Only Stores,Specialty Retailers: Other,1999,-232,18200
Technology,F5 Networks,Network and Other Communications Equipment,1920,365,4178
Telecommunications,Equinix,Telecommunications,2726,188,5042
Transportation,Roadrunner Transportation Systems,Transportation and Logistics,1995,48,4502
Wholesalers,BlueLinx Holdings,Wholesalers: Diversified,1917,-12,1600

In [21]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
fortune.head()

sectors = fortune.groupby("Sector")
sectors.get_group(name="Energy")
sectors.get_group(name="Technology")

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
18,Amazon.com,Technology,Internet Services and Retailing,107006,596,230800
20,HP,Technology,"Computers, Office Equipment",103355,4554,287000
25,Microsoft,Technology,Computer Software,93580,12193,118000
31,IBM,Technology,Information Technology Services,82461,13190,411798
...,...,...,...,...,...,...
970,Rackspace Hosting,Technology,Internet Services and Retailing,2001,126,6189
971,VeriFone Systems,Technology,"Computers, Office Equipment",2001,79,5400
975,Super Micro Computer,Technology,"Computers, Office Equipment",1991,102,2285
984,Nuance Communications,Technology,Computer Software,1931,-115,13500
990,F5 Networks,Technology,Network and Other Communications Equipment,1920,365,4178