# Merging dataframes

In [1]:
import pandas as pd

In [2]:
foods = pd.read_csv("restaurant_foods.csv")
customers = pd.read_csv("restaurant_customers.csv")
week1 = pd.read_csv("restaurant_week_1_sales.csv")
week2 = pd.read_csv("restaurant_week_2_sales.csv")

week1.head()
week2.head()
len(week1)
len(week2)
pd.concat([week1, week2])
pd.concat([week1, week2], ignore_index=True)
pd.concat([week1, week2], keys=["Week 1", "Week 2"]).sort_index()

            Customer ID  Food ID
Week 1 0            537        9
       1             97        4
       2            658        1
       3            202        2
       4            155        9
...                 ...      ...
Week 2 245          783       10
       246          556       10
       247          547        9
       248          252        9
       249          249        6

[500 rows x 2 columns]

In [10]:
df1 = pd.DataFrame([1, 2, 3], columns=["A"])
df2 = pd.DataFrame([4, 5, 6], columns=["B"])

pd.concat([df1, df2])
pd.concat([df1, df2], axis="columns")
pd.concat([df1, df2], axis=1)

   A  B
0  1  4
1  2  5
2  3  6