# MultiIndex

In [1]:
import pandas as pd

In [9]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d")
bigmac.head()
bigmac.dtypes
bigmac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1386 non-null   datetime64[ns]
 1   Country              1386 non-null   object
 2   Price in US Dollars  1386 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 32.6+ KB

In [21]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d")
bigmac.head()

bigmac.set_index("Date")
bigmac.set_index("Country")
bigmac.set_index(keys=["Date", "Country"])
bigmac.set_index(keys=["Country", "Date"]).sort_index()
bigmac.nunique()
bigmac = bigmac.set_index(keys=["Date", "Country"]).sort_index()

bigmac.head()

bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()

bigmac.head()

bigmac.index
bigmac.index.names
bigmac.index[0]

(Timestamp('2000-04-01 00:00:00'), 'Argentina')

In [10]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()
bigmac.head()


bigmac.index.get_level_values("Date")
bigmac.index.get_level_values(0)

bigmac.index.get_level_values("Country")
bigmac.index.get_level_values(1)

Index(['Argentina', 'Australia', 'Brazil', 'Britain', 'Canada', 'Chile',
       'China', 'Czech Republic', 'Denmark', 'Euro area',
       ...
       'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'Ukraine',
       'United Arab Emirates', 'United States', 'Uruguay', 'Vietnam'],
      dtype='object', name='Country', length=1386)

In [17]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()
bigmac.head()

bigmac.index.set_names(names="Time", level=0)
bigmac.index.set_names(names="Location", level=1)
bigmac.index.set_names(names=["Time", "Location"])
bigmac.index = bigmac.index.set_names(names=["Time", "Location"])
bigmac.head()

                      Price in US Dollars
Time       Location
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [7]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"])
bigmac.head()

bigmac.sort_index(ascending=False)
bigmac.sort_index(ascending=[True, False])
bigmac.sort_index(ascending=[False, True])

                          Price in US Dollars
Date       Country
2020-07-01 Argentina                 3.509232
           Australia                 4.578450
           Azerbaijan                2.324897
           Bahrain                   3.713035
           Brazil                    3.913528
...                                       ...
2000-04-01 Sweden                    2.714932
           Switzerland               3.470588
           Taiwan                    2.287582
           Thailand                  1.447368
           United States             2.510000

[1386 rows x 1 columns]

In [10]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()
bigmac.head()

type(1,)
type((1,))
1, 2
(1, 2)

bigmac.iloc[2]
bigmac.loc["2000-04-01"]
bigmac.loc["2000-04-01", "Canada"]
bigmac.loc["2000-04-01", "Price in US Dollars"]
bigmac.loc[("2000-04-01", "Canada")]
bigmac.loc[("2000-04-01", "Canada"), "Price in US Dollars"]

bigmac.loc[("2000-04-01", "Hungary"): ("2000-04-01", "Poland")]
bigmac.loc[("2019-07-09", "Hungary"):]
bigmac.loc[("2012-01-01", "Brazil"): ("2013-07-01", "Turkey"), "Price in US Dollars"]

Date        Country
2012-01-01  Brazil         5.678670
            Britain        3.823395
            Canada         4.632940
            Chile          4.050983
            China          2.438445
                             ...
2013-07-01  Sweden         6.156874
            Switzerland    6.719041
            Taiwan         2.630834
            Thailand       2.845723
            Turkey         4.342384
Name: Price in US Dollars, Length: 160, dtype: float64

In [14]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()
bigmac.head()

start = ("2018-01-01", "China")
end = ("2018-01-01", "Denmark")
bigmac.loc[start: end].transpose()
bigmac.loc[start: end].transpose().columns

MultiIndex([('2018-01-01',          'China'),
            ('2018-01-01',       'Colombia'),
            ('2018-01-01',     'Costa Rica'),
            ('2018-01-01', 'Czech Republic'),
            ('2018-01-01',        'Denmark')],
           names=['Date', 'Country'])

In [12]:
pd.read_csv("worldstats.csv")
pd.read_csv("worldstats.csv").nunique()
world = pd.read_csv("worldstats.csv", index_col=["year", "country"]).sort_index()
world.head()

world.stack()
type(world.stack())
world.stack().to_frame()

                                        0
year country
1960 Afghanistan Population  8.994793e+06
                 GDP         5.377778e+08
     Algeria     Population  1.112489e+07
                 GDP         2.723638e+09
     Australia   Population  1.027648e+07
...                                   ...
2015 World       GDP         7.343364e+13
     Zambia      Population  1.621177e+07
                 GDP         2.120156e+10
     Zimbabwe    Population  1.560275e+07
                 GDP         1.389294e+10

[22422 rows x 1 columns]

In [37]:
world = pd.read_csv("worldstats.csv", index_col=["year", "country"]).sort_index().stack()
world.head()

world.index.names

world.unstack().columns
world.unstack().unstack()
world.unstack().unstack().columns
world.unstack(level=0)
world.unstack(level=1)
world.unstack(level=2)
world.unstack(level="year")
world.unstack(level="country")
world.unstack(level=-1)
world.unstack(level=-3)

world.unstack(level=[1, 0])
world.unstack(level=["country", "year"])
world.unstack(level=[0, 1])
world.unstack(["year", "country"]).sort_index(axis=1, ascending=False)

year                2015                                                 \
country         Zimbabwe        Zambia         World West Bank and Gaza
Population  1.560275e+07  1.621177e+07  7.346633e+09       4.422143e+06
GDP         1.389294e+10  2.120156e+10  7.343364e+13       1.267740e+10

year                                                                      \
country          Vietnam    Uzbekistan       Uruguay Upper middle income
Population  9.170380e+07  3.129950e+07  3.431555e+06        2.550326e+09
GDP         1.935994e+11  6.673280e+10  5.344270e+10        1.973288e+13

year                                     ...          1960                \
country    United States United Kingdom  ...       Bermuda         Benin
Population  3.214188e+08   6.513823e+07  ...  4.440000e+04  2.431620e+06
GDP         1.794700e+13   2.848755e+12  ...  8.446665e+07  2.261956e+08

year                                                                \
country           Belize       Belgium    Bangladesh  Bahamas, The
Population  9.206800e+04  9.153489e+06  4.820070e+07  1.095260e+05
GDP         2.807248e+07  1.165872e+10  4.274894e+09  1.698023e+08

year
country          Austria     Australia       Algeria   Afghanistan
Population  7.047539e+06  1.027648e+07  1.112489e+07  8.994793e+06
GDP         6.592694e+09  1.856759e+10  2.723638e+09  5.377778e+08

[2 rows x 11211 columns]