In [1]:
import pandas as pd

In [7]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago.head()
chicago.info()
chicago.nunique()
chicago["Department"] = chicago["Department"].astype("category")
chicago.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32062 entries, 0 to 32061
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  object
 3   Employee Annual Salary  32062 non-null  object
dtypes: object(4)
memory usage: 1.2+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 32062 entries, 0 to 32061
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  category
 3   Employee Annual Salary  32062 non-null  object
dtypes: category(1), object(3)
memory usage: 1.0+ MB

In [25]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

"boris".upper()
"boris the genius".title()

chicago["Position Title"].str.lower()
chicago["Position Title"].str.upper()
# chicago["Position Title"].upper()
chicago["Position Title"].str.title()
chicago["Position Title"].str.len()
chicago["Position Title"].str.title().str.len()
chicago["Position Title"].str.strip()
chicago["Position Title"].str.lstrip()
chicago["Position Title"].str.rstrip()
chicago["Department"].str.replace("MGMNT", "MANAGEMENT").str.title()

0        Water Management
1                  Police
2                  Police
3        General Services
4        Water Management
               ...
32057    General Services
32058              Police
32059              Police
32060              Police
32061                Doit
Name: Department, Length: 32062, dtype: object

In [12]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

water = chicago["Position Title"].str.lower().str.contains("water") 
chicago[water]
civil = chicago["Position Title"].str.lower().str.startswith("civil")
chicago.loc[civil]
iv = chicago["Position Title"].str.lower().str.endswith("iv")
chicago[iv]

,Name,Position Title,Department,Employee Annual Salary
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
34,"ABRAHAM, GIRLEY T",CIVIL ENGINEER IV,WATER MGMNT,$106836.00
145,"ADAMS, SHERYLL A",LIBRARIAN IV,PUBLIC LIBRARY,$97812.00
147,"ADAMS, TANERA C",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
166,"ADENI, MOHAMED K",ACCOUNTANT IV,FINANCE,$97812.00
...,...,...,...,...
31777,"ZAFIRIS, CHRISTOPHER",ARCHITECT IV,DISABILITIES,$106836.00
31797,"ZAKE, JOSHUA S",CIVIL ENGINEER IV,TRANSPORTN,$106836.00
31870,"ZAVALA, FERNANDO",ACCOUNTANT IV,FINANCE,$97812.00
31884,"ZAWADSKI, JAMES",CLERK IV,LAW,$68028.00
32008,"ZOTTA, SANDINO",MECHANICAL ENGINEER IV,WATER MGMNT,$106836.00

In [2]:
chicago = pd.read_csv("chicago.csv", index_col="Name").dropna(how="all").sort_index()
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

type(chicago.index)
chicago.index = chicago.index.str.strip().str.title()
chicago
chicago.columns = chicago.columns.str.upper()
chicago

,Position Title,Department,Employee Annual Salary
Name,,,
"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [8]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

chicago["Position Title"].str.split(" ").str.get(0).value_counts()

Position Title
POLICE                10856
FIREFIGHTER-EMT        1509
SERGEANT               1186
POOL                    918
FIREFIGHTER             810
                      ...
DEVELOPMENT               1
PURCHASING                1
MOBILE                    1
ANALYST                   1
TELECOMMUNICATIONS        1
Name: count, Length: 320, dtype: int64

In [18]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

chicago["Name"].str.title().str.split(", ").str.get(1).str.strip().str.split(" ").str.get(0).value_counts()

Name
Michael    1153
John        899
James       676
Robert      622
Joseph      537
           ...
Samera        1
Kefeng        1
Edina         1
Tecla         1
Lilya         1
Name: count, Length: 5091, dtype: int64

In [13]:
chicago = pd.read_csv("chicago.csv").dropna(how="all")
chicago["Department"] = chicago["Department"].astype("category")
chicago.head()

chicago[["Last Name", "First Name"]] = chicago["Name"].str.split(",", expand=True)
chicago.head()

chicago[["Primary Title", "Secondary Title"]] = chicago["Position Title"].str.split(" ", expand=True, n=1)
chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Last Name,First Name,Primary Title,Secondary Title
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00,AARON,ELVIA J,WATER,RATE TAKER
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00,AARON,JEFFERY M,POLICE,OFFICER
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00,AARON,KARINA,POLICE,OFFICER
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00,AARON,KIMBERLEI R,CHIEF,CONTRACT EXPEDITER
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00,ABAD JR,VICENTE M,CIVIL,ENGINEER IV