# Working with Dates and Times

In [1]:
import pandas as pd
import datetime as dt

In [21]:
someday = dt.date(2025, 12, 15)

someday.year
someday.month
someday.day

dt.datetime(2025, 12, 15)
dt.datetime(2025, 12, 15, 8)
dt.datetime(2025, 12, 15, 8, 13)
dt.datetime(2025, 12, 15, 8, 13, 59)

sometime = dt.datetime(2025, 12, 15, 8, 13, 59)
sometime.year
sometime.month
sometime.day
sometime.hour
sometime.minute
sometime.second
sometime.microsecond

0

In [8]:
pd.Timestamp(2027, 3, 12)
pd.Timestamp(2027, 3, 12, 18, 23, 49)
pd.Timestamp(dt.date(2028, 10, 23))
pd.Timestamp(dt.datetime(2028, 10, 23, 14, 35))
pd.Timestamp("2025-01-01")
pd.Timestamp("2025/01/01")
pd.Timestamp("2025-03-08 08:35:15")
pd.Series([pd.Timestamp("2025-03-08 08:35:15")]).iloc[0]
pd.DatetimeIndex(["2025-01-01", "2025-02-01", "2025-03-01"])
index = pd.DatetimeIndex([
    dt.date(2026, 1, 10),
    dt.date(2026, 2, 20)
])
# index
index[0]
type(index[0])

pandas._libs.tslibs.timestamps.Timestamp

In [33]:
pd.date_range(start="2025-01-01", end="2025-01-07")
pd.date_range(start="2025-01-01", end="2025-01-07", freq="D")
pd.date_range(start="2025-01-01", end="2025-01-07", freq="2D")
# Business day Mon-Fri
pd.date_range(start="2025-01-01", end="2025-01-07", freq="B")
# By default week starts on Sun
pd.date_range(start="2025-01-01", end="2025-01-31", freq="W")
# Start on Friday and jump weekly
pd.date_range(start="2025-01-01", end="2025-01-31", freq="W-FRI")
pd.date_range(start="2025-01-01", end="2025-01-31", freq="W-THU")
pd.date_range(start="2025-01-01", end="2025-01-31", freq="h")
pd.date_range(start="2025-01-01", end="2025-01-31", freq="6h")
# Month end
pd.date_range(start="2025-01-01", end="2025-12-31", freq="ME")
# Month start
pd.date_range(start="2025-01-01", end="2025-12-31", freq="MS")
# Year end
pd.date_range(start="2025-01-01", end="2050-12-31", freq="YE")
# Generate 25 days.
pd.date_range(start="2012-09-09", freq="D", periods=25)
pd.date_range(start="2012-09-09", freq="3D", periods=40)
pd.date_range(start="2012-09-09", freq="B", periods=180)
pd.date_range(end="2013-10-31", freq="D", periods=20)
pd.date_range(end="2016-12-31", freq="B", periods=75)
pd.date_range(end="1991-04-12", freq="W-FRI", periods=75)

DatetimeIndex(['1989-11-10', '1989-11-17', '1989-11-24', '1989-12-01',
               '1989-12-08', '1989-12-15', '1989-12-22', '1989-12-29',
               '1990-01-05', '1990-01-12', '1990-01-19', '1990-01-26',
               '1990-02-02', '1990-02-09', '1990-02-16', '1990-02-23',
               '1990-03-02', '1990-03-09', '1990-03-16', '1990-03-23',
               '1990-03-30', '1990-04-06', '1990-04-13', '1990-04-20',
               '1990-04-27', '1990-05-04', '1990-05-11', '1990-05-18',
               '1990-05-25', '1990-06-01', '1990-06-08', '1990-06-15',
               '1990-06-22', '1990-06-29', '1990-07-06', '1990-07-13',
               '1990-07-20', '1990-07-27', '1990-08-03', '1990-08-10',
               '1990-08-17', '1990-08-24', '1990-08-31', '1990-09-07',
               '1990-09-14', '1990-09-21', '1990-09-28', '1990-10-05',
               '1990-10-12', '1990-10-19', '1990-10-26', '1990-11-02',
               '1990-11-09', '1990-11-16', '1990-11-23', '1990-11-30',
               '1990-12-07', '1990-12-14', '1990-12-21', '1990-12-28',
               '1991-01-04', '1991-01-11', '1991-01-18', '1991-01-25',
               '1991-02-01', '1991-02-08', '1991-02-15', '1991-02-22',
               '1991-03-01', '1991-03-08', '1991-03-15', '1991-03-22',
               '1991-03-29', '1991-04-05', '1991-04-12'],
              dtype='datetime64[ns]', freq='W-FRI')

In [8]:
bunch_of_dates = pd.Series(pd.date_range(start="2000-01-01", end="2020-12-31", freq="24D 3h"))

bunch_of_dates.dt.day
bunch_of_dates.dt.month
bunch_of_dates.dt.year
bunch_of_dates.dt.hour
bunch_of_dates.dt.day_of_year
bunch_of_dates.dt.day_name()
bunch_of_dates.dt.is_month_end
bunch_of_dates[bunch_of_dates.dt.is_quarter_start]

0     2000-01-01 00:00:00
106   2007-01-01 06:00:00
212   2014-01-01 12:00:00
299   2019-10-01 09:00:00
dtype: datetime64[ns]

In [27]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()

stocks.head()
stocks.iloc[300]
stocks.index
stocks.loc["2014-03-04"]
stocks.loc[pd.Timestamp(2014, 3, 4)]
stocks.loc["2014-03-04":"2014-12-31"]
stocks.loc[pd.Timestamp(2014, 3, 4):pd.Timestamp(2014, 12, 31)]
stocks.truncate("2014-03-04", "2014-12-31")
stocks.loc["2014-03-04", "Close"]
stocks.loc["2014-03-04", "High":"Close"]
stocks.loc[pd.Timestamp(2014, 3, 4):pd.Timestamp(2014, 12, 31), "High":"Close"]

               High      Low    Close
Date
2014-03-04  129.827  128.802  129.329
2014-03-05  130.344  129.319  129.807
2014-03-06  130.676  129.631  130.159
2014-03-07  131.047  129.837  130.198
2014-03-10  130.666  128.890  129.309
...             ...      ...      ...
2014-12-24  115.188  114.183  114.359
2014-12-26  115.257  114.495  114.700
2014-12-29  114.700  112.661  113.412
2014-12-30  113.656  112.934  113.109
2014-12-31  114.105  113.304  113.354

[211 rows x 3 columns]

In [16]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.head()
stocks.index + pd.DateOffset(days=5)
stocks.index - pd.DateOffset(days=5)
stocks.index + pd.DateOffset(months=3)
stocks.index - pd.DateOffset(years=1)
stocks.index + pd.DateOffset(hours=7)
stocks.index + pd.DateOffset(years=1, months=3, days=2, hours=14, minutes=23, seconds=12)

pd.date_range(start="1991-04-12", end="2023-04-12", freq=pd.DateOffset(years=1))
birthdays = pd.date_range(start="1991-04-12", end="2023-04-12", freq=pd.DateOffset(years=1))
stocks[stocks.index.isin(birthdays)]

                 Open       High        Low      Close        Volume
Date
1991-04-12   18.16780   18.16780   17.69540   17.75200  2.164536e+07
1993-04-12    8.30500    8.48788    8.28665    8.34598  8.518730e+06
1994-04-12    8.79793    8.81911    8.59455    8.65281  1.149508e+07
1995-04-12   14.16070   14.34310   14.09330   14.25620  1.158640e+07
1996-04-12   18.86360   18.92410   18.02330   18.25170  4.724783e+07
1999-04-12   60.07580   60.10990   59.27160   60.05430  1.366693e+07
2000-04-12   78.30890   78.30890   73.13650   74.49310  1.352295e+07
2001-04-12   63.33930   64.06240   62.51650   63.20750  1.429048e+07
2002-04-12   57.53060   57.79410   55.45480   56.24140  2.405615e+07
2004-04-12   61.43420   61.99840   61.36590   61.59330  4.736957e+06
2005-04-12   56.44050   56.66400   55.95930   56.34190  1.286059e+07
2006-04-12   53.28730   53.46300   52.97880   53.05790  5.943571e+06
2007-04-12   62.43660   62.95670   62.10960   62.86010  1.078356e+07
2010-04-12   84.48650   84.73830   84.26890   84.34410  6.076087e+06
2011-04-12  107.36100  107.59500  106.65800  107.28300  5.876340e+06
2012-04-12  135.49600  137.33200  135.37000  137.18500  4.384856e+06
2013-04-12  143.23600  143.71500  142.54300  143.64600  4.658051e+06
2016-04-12  110.27900  110.65000  109.53700  110.28900  4.874036e+06
2017-04-12  130.58800  130.71500  129.80700  130.29600  4.292101e+06
2018-04-12  124.55700  126.31400  124.48900  125.58200  7.097073e+06
2019-04-12  120.04800  120.18500  119.57000  120.10700  3.484076e+06
2021-04-12  124.11800  124.43900  123.03400  123.71800  4.083806e+06
2022-04-12  121.89300  122.78100  121.09200  121.47300  2.790840e+06
2023-04-12  130.40000  130.88570  128.17000  128.54000  3.957542e+06

In [28]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.head()
stocks.index + pd.tseries.offsets.MonthEnd()
stocks.index - pd.tseries.offsets.MonthEnd()
stocks.index + pd.tseries.offsets.QuarterEnd()
stocks.index - pd.tseries.offsets.QuarterEnd()
stocks.index + pd.tseries.offsets.QuarterBegin(startingMonth=1)
stocks.index - pd.tseries.offsets.QuarterBegin(startingMonth=1)
stocks.index + pd.tseries.offsets.YearEnd()
stocks.index + pd.tseries.offsets.YearBegin()

DatetimeIndex(['1963-01-01', '1963-01-01', '1963-01-01', '1963-01-01',
               '1963-01-01', '1963-01-01', '1963-01-01', '1963-01-01',
               '1963-01-01', '1963-01-01',
               ...
               '2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01',
               '2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01',
               '2024-01-01', '2024-01-01'],
              dtype='datetime64[ns]', name='Date', length=15546, freq=None)